//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicle_Fleet_Management.Repositoryes.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public int IDRoute { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string StartLocation { get; set; }
        public string EndLocation { get; set; }
        public Nullable<int> Distance { get; set; }
        public Nullable<double> FuelSpent { get; set; }
        public int FK_TravelWarrents { get; set; }
    
        public virtual TravelWarrent TravelWarrent { get; set; }
    }
}
