//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicle_Fleet_Management.Repositoryes.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelExpence
    {
        public int IDTravelExpence { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public int FK_TravelWarrents { get; set; }
        public int FK_Items { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual TravelWarrent TravelWarrent { get; set; }
    }
}
