//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicle_Fleet_Management.Repositoryes.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelWarrent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TravelWarrent()
        {
            this.Routes = new HashSet<Route>();
            this.TravelExpences = new HashSet<TravelExpence>();
        }
    
        public int IDTravelWarrent { get; set; }
        public string RouteDescription { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int FK_Drivers { get; set; }
        public int FK_Vehicles { get; set; }
        public byte FK_TravelWarrantStates { get; set; }
    
        public virtual Driver Driver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Route> Routes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelExpence> TravelExpences { get; set; }
        public virtual TravelWarrantState TravelWarrantState { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
