//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicle_Fleet_Management.Repositoryes.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleService
    {
        public int IDVehicleService { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Price { get; set; }
        public int FK_Vehicles { get; set; }

        public override string ToString()
        {
            return IDVehicleService+"/"+ Description;
        }
        public virtual Vehicle Vehicle { get; set; }
    }
}
