//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicle_Fleet_Management.Repositoryes.entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VehicleFleetManagementEntities : DbContext
    {
        public VehicleFleetManagementEntities()
            : base("name=VehicleFleetManagementEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Route> Routes { get; set; }
        public virtual DbSet<TravelExpence> TravelExpences { get; set; }
        public virtual DbSet<TravelWarrantState> TravelWarrantStates { get; set; }
        public virtual DbSet<TravelWarrent> TravelWarrents { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<VehicleService> VehicleServices { get; set; }
    }
}
